apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

configMapGenerator:
  - name: portfolio-backend-env
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - patch-deployment-configmap.yaml

images:
  - name: portfolio-backend
    newName: portfolio-backend
    newTag: local
