apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend
spec:
  template:
    spec:
      containers:
        - name: portfolio-backend
          envFrom:
            - configMapRef:
                name: portfolio-backend-env
